from tkinter import*

root = Tk()
root.title("Pyhon GUI")
frame = Frame(root, width=700, height=700)

menubar = Menu(root)
filemenu = Menu(menubar, tearoff=0)
filemenu.add_command(label="New File                         Ctrl+N")
filemenu.add_command(label="Open                              Ctrl+O")
filemenu.add_command(label="Open Module                Alt+M")
filemenu.add_command(label="Recent File")
filemenu.add_command(label="Module Browser           Alt+C")
filemenu.add_command(label="Path Browser")
filemenu.add_separator()
filemenu.add_command(label="Save                               Ctrl+S")
filemenu.add_command(label="Save as                          Ctrl+Shift+S")
filemenu.add_command(label="Save as copy...              Alt+Shift+S")
filemenu.add_separator()
filemenu.add_command(label="Print Window               Ctrl+P")
filemenu.add_separator()
filemenu.add_command(label="Close                            Alt+F4")
filemenu.add_command(label="Exit                                Ctrl+Q")
menubar.add_cascade(label="File", menu=filemenu)

editmenu = Menu(menubar, tearoff=0)
editmenu.add_command(label="Undo \t\t\t Ctrl+Z")
editmenu.add_command(label="Redo")
editmenu.add_separator()
editmenu.add_command(label="Cut")
editmenu.add_command(label="Copy")
editmenu.add_command(label="Paste")
editmenu.add_command(label="Select all")
editmenu.add_separator()
editmenu.add_command(label="Find...")
editmenu.add_command(label="Find Again")
editmenu.add_command(label="Find Selection")
editmenu.add_command(label="Find in Files...")
menubar.add_cascade(label="Edit", menu=editmenu)

formatmenu = Menu(menubar, tearoff=0)
formatmenu.add_command(label="Indent Region")
formatmenu.add_command(label="Dedent Region")
formatmenu.add_command(label="Comment Out Region")
formatmenu.add_command(label="Uncomment Region")
formatmenu.add_command(label="Tabify Region")
formatmenu.add_command(label="Untabify Region")
formatmenu.add_command(label="Toggle Tabs")
formatmenu.add_command(label="New Indent Width")
formatmenu.add_command(label="Format Paragraph")
formatmenu.add_command(label="Strip Trailing Whitespasce")
menubar.add_cascade(label="Format",menu=formatmenu)

runmenu = Menu(menubar, tearoff=0)
runmenu.add_command(label="Python Shell")
runmenu.add_command(label="Check Module")
runmenu.add_command(label="Run Module")
runmenu.add_command(label="Run Customized")
runmenu.add_cascade(label="Run", menu=runmenu)

optionsmenu = Menu(menubar, tearoff=0)
optionsmenu.add_command(label="Configure IDLE")
optionsmenu.add_separator()
optionsmenu.add_command(label="Show code context")
optionsmenu.add_command(label="Zoom height")
menubar.add_cascade(label="Options", menu=optionsmenu)

windowmenu = Menu(menubar,tearoff=0)
windowmenu.add_command(label="G:\SADIQUL ISLAM\PROGRAMMING\P_PROGRAM\MyProject\GuiProgram")
menubar.add_cascade(label="Window", menu=windowmenu)

helpmenu = Menu(menubar, tearoff=0)
helpmenu.add_command(label="About IDLE")
helpmenu.add_separator()
helpmenu.add_command(label="IDLE Help")
helpmenu.add_command(label="Python Docs\t F1")
helpmenu.add_command(label="Turtle Demo")
menubar.add_cascade(label="Help", menu=helpmenu)


root.config(menu=menubar)
frame.pack()
root.mainloop()

